version: '3.3'

#Persistência do container
volumes:
  database:

services:
  app:
    build: .
    container_name: "opovorequer-api"
    command: sh -c "npm start"
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:latest
    ports:
      - 3737:5432
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - database:/var/lib/postgresql/db
      #Problema de memória em produção
      - type: tmpfs
        target: /dev/shm
    
